// Copyright 2017-2022 @soul-wallet/extension-inject authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@soul-wallet/extension-inject', path: 'auto', type: 'auto', version: '1.1.17-0' };
