// Copyright 2023 @soul-wallet/web-runner authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/web-runner', path: 'auto', type: 'auto', version: '1.1.17-0' };
