// Copyright 2023 @soul-wallet/extension-dapp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@soul-wallet/extension-dapp', path: 'auto', type: 'auto', version: '1.0.0' };
